/**
 * Softomate Person API
 * This is a API for Softomate testwork
 *
 * OpenAPI spec version: 1.0.0
 * Contact: imail.for.iwork@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface ErrorMessage {
    code?: string;

    message?: string;

}
